backend:
  name: git-gateway
  branch: main
publish_mode: simple

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

site_url: "/"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "content/settings.json"
        label: "Settings"
        name: "settings"
        fields:
          - {label: "Donate URL (Alumni)", name: "donate.url", widget: "string", required: false}
          - {label: "Donate URL (Parents/Family)", name: "donate.url_family", widget: "string", required: false}
          - {label: "Forms mode", name: "forms.mode", widget: "select", options: ["netlify","formspree","disabled"], required: false}
          - {label: "Formspree Alumni Endpoint", name: "forms.alumni_endpoint", widget: "string", required: false}
          - {label: "Formspree Family Endpoint", name: "forms.family_endpoint", widget: "string", required: false}
          - {label: "Alumni RSVP URL", name: "alumni.homecoming2025.rsvp_url", widget: "string", required: false}

  - name: "leadership"
    label: "Leadership"
    files:
      - file: "content/leadership.json"
        label: "Leadership Members"
        name: "leadership"
        fields:
          - label: "Members"
            name: "members"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}
              - {label: "Email", name: "email", widget: "string", required: false}
              - {label: "Photo", name: "photo", widget: "image", required: false}

  - name: "gallery"
    label: "Gallery"
    files:
      - file: "content/gallery/index.json"
        label: "Gallery Items"
        name: "gallery"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Photo", name: "photo", widget: "image"}

  - name: "events"
    label: "Events"
    files:
      - file: "content/events/brotherhood.json"
        label: "Brotherhood"
        name: "events_brotherhood"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Date (YYYY-MM-DD)", name: "date", widget: "string", required: false}
              - {label: "Location", name: "location", widget: "string", required: false}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Photo", name: "photo", widget: "image", required: false}

      - file: "content/events/community-service.json"
        label: "Community Service"
        name: "events_community_service"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Date (YYYY-MM-DD)", name: "date", widget: "string", required: false}
              - {label: "Location", name: "location", widget: "string", required: false}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Photo", name: "photo", widget: "image", required: false}

      - file: "content/events/philanthropy.json"
        label: "Philanthropy"
        name: "events_philanthropy"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Date (YYYY-MM-DD)", name: "date", widget: "string", required: false}
              - {label: "Location", name: "location", widget: "string", required: false}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Photo", name: "photo", widget: "image", required: false}

      - file: "content/events/fundraising.json"
        label: "Fundraising"
        name: "events_fundraising"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Date (YYYY-MM-DD)", name: "date", widget: "string", required: false}
              - {label: "Location", name: "location", widget: "string", required: false}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Photo", name: "photo", widget: "image", required: false}
