backend:
  name: git-gateway
  branch: main

publish_mode: simple        # instant publish (no PR workflow)

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    file: "content/settings.json"
    fields:
      - label: "Donate"
        name: donate
        widget: object
        fields:
          - { label: "Alumni Link", name: url, widget: string }
          - { label: "Family/Friends Link", name: url_family, widget: string, required: false }
          - { label: "Blurb", name: blurb, widget: text, required: false }
      - label: "Forms"
        name: forms
        widget: object
        fields:
          - { label: "Mode", name: mode, widget: select, options: ["netlify","formspree","disabled"], default: "netlify" }
          - { label: "Alumni Formspree Endpoint", name: alumni_endpoint, widget: string, required: false }
          - { label: "Family Formspree Endpoint", name: family_endpoint, widget: string, required: false }
      - label: "Goals"
        name: goals
        widget: object
        fields:
          - { label: "Use server function", name: use_function, widget: boolean, default: false }
      - label: "Alumni"
        name: alumni
        widget: object
        fields:
          - label: "Homecoming 2025"
            name: homecoming2025
            widget: object
            fields:
              - { label: "RSVP URL", name: rsvp_url, widget: string, required: false }

  - name: "leadership"
    label: "Leadership"
    file: "content/leadership.json"
    fields:
      - label: "Members"
        name: members
        widget: list
        fields:
          - { label: "Name", name: name }
          - { label: "Role/Position", name: role }
          - { label: "Email", name: email, required: false }
          - { label: "Photo", name: photo, widget: image, required: false }

  - name: "donors"
    label: "Donor Wall"
    file: "content/donors.json"
    fields:
      - label: Donors
        name: donors
        widget: list
        fields:
          - { name: type, label: Type, widget: select, options: ["alumni","family"] }
          - { name: name, label: Name }
          - { name: class_year, label: Class Year (alumni), required: false }
          - { name: related_to, label: Related To (family), required: false }
          - { name: message, label: Public Message, widget: text, required: false }

  - name: "goals"
    label: "Goals"
    file: "content/goals.json"
    fields:
      - label: Goals
        name: goals
        widget: list
        fields:
          - { name: slug, label: Slug }
          - { name: title, label: Title }
          - { name: goal_amount, label: Goal Amount, widget: number, value_type: int }
          - { name: current_amount, label: Current Amount, widget: number, value_type: int, required: false }
          - { name: source, label: Source, widget: select, options: ["manual"], default: "manual" }

  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    extension: "json"
    format: "json"
    fields:
      - { label: Title, name: title }
      - { label: Description, name: description, widget: text, required: false }
      - { label: Photo, name: photo, widget: image }

  # Events by category (you can add/remove as needed)
  - name: "events_alumni"
    label: "Events – Alumni"
    folder: "content/events/alumni"
    create: true
    extension: "json"
    format: "json"
    fields:
      - { label: Title, name: title }
      - { label: Date (YYYY-MM-DD), name: date }
      - { l
